In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import sys
import os
from datasets import load_dataset

root_path = os.path.abspath(os.path.join(".."))
if root_path not in sys.path:
    sys.path.append(root_path)

from utils import standardize_model_names # noqa: E402

In [9]:
csv_url = "https://huggingface.co/datasets/mehmetdavut/RubyCraft-3.4-Eval-Logs/resolve/main/ic_before_after.csv"
df_csv = pd.read_csv(csv_url)
df_csv = standardize_model_names(df_csv, model_column="model")

df_csv = df_csv[~df_csv["model"].str.contains("teacher", case=False, na=False)].copy()

In [11]:
dataset_meta = load_dataset(
    "mehmetdavut/RubyCraft-3.4-Eval-Logs", 
    "intrinsic_capability_humaneval", 
    split="train"
)
df_meta = dataset_meta.to_pandas()
df_meta = standardize_model_names(df_meta, model_column="model_architecture")
df_meta = df_meta[~df_meta["model_role"].str.contains("Teacher", case=False, na=False)].copy()

df_meta["passed_bool"] = df_meta["raw_avg_score"] > 0
meta_grouped = df_meta.groupby([
    "experiment_id", "Architecture", "dataset_size", "data_split", "quantization"
])["passed_bool"].sum().reset_index()
meta_grouped.rename(columns={"passed_bool": "raw_score"}, inplace=True)

In [12]:
meta_grouped = meta_grouped.sort_values(["experiment_id", "Architecture", "raw_score", "data_split"])
meta_grouped["rank"] = meta_grouped.groupby(["experiment_id", "Architecture"])["raw_score"].rank(method="first")

df_csv = df_csv.sort_values(["experiment", "Architecture", "before_passed", "model"])
df_csv["rank"] = df_csv.groupby(["experiment", "Architecture"])["before_passed"].rank(method="first")

df_merged = df_csv.merge(
    meta_grouped,
    left_on=["experiment", "Architecture", "rank"],
    right_on=["experiment_id", "Architecture", "rank"],
    how="left"
)

In [13]:
base_mask = df_merged["data_split"].isna() | (df_merged["data_split"] == "Base")
df_merged.loc[base_mask, "dataset_size"] = "-"
df_merged.loc[base_mask, "data_split"] = "Vanilla"
df_merged.loc[base_mask, "quantization"] = "-"

In [14]:
df_merged["after_passed"] = df_merged["after_passed"].fillna(0).astype(int)
df_merged["before_passed"] = df_merged["before_passed"].fillna(0).astype(int)

tier_col = "Tier_x" if "Tier_x" in df_merged.columns else "Tier"

df_solved = df_merged[[
    "experiment", "Architecture", tier_col, 
    "dataset_size", "data_split", "quantization", 
    "before_passed", "after_passed"
]].copy()

df_solved.rename(columns={tier_col: "Tier"}, inplace=True)
df_solved = df_solved.sort_values(by="after_passed", ascending=False).reset_index(drop=True)

display(df_solved.head(50))

,experiment,Architecture,Tier,dataset_size,data_split,quantization,before_passed,after_passed
0,exp-111,Qwen-Coder,Big (≥ 7B),-,Vanilla,-,15,101
1,exp-113,Qwen-Coder,Big (≥ 7B),-,Vanilla,-,15,101
2,exp-112,Qwen-Coder,Big (≥ 7B),-,Vanilla,-,15,101
3,exp-114,Qwen-Coder,Big (≥ 7B),-,Vanilla,-,15,101
4,exp-110,Qwen-Coder,Big (≥ 7B),-,Vanilla,-,15,101
5,exp-109,Qwen-Coder,Big (≥ 7B),-,Vanilla,-,15,101
6,exp-112,Qwen,Big (≥ 7B),-,Vanilla,-,52,86
7,exp-114,Qwen,Big (≥ 7B),-,Vanilla,-,52,86
8,exp-109,Qwen,Big (≥ 7B),-,Vanilla,-,52,86
9,exp-113,Qwen-Coder,Big (≥ 7B),1K,ALL,16-bit,73,86
10,exp-112,Qwen-Coder,Big (≥ 7B),5K,ALL,8-bit,73,86
11,exp-113,Qwen,Big (≥ 7B),-,Vanilla,-,52,86
12,exp-111,Qwen,Big (≥ 7B),-,Vanilla,-,52,86
13,exp-110,Qwen,Big (≥ 7B),-,Vanilla,-,52,86
14,exp-110,Qwen-Coder,Big (≥ 7B),5K,ALL,4-bit,73,85
15,exp-114,Qwen-Coder,Big (≥ 7B),5K,ALL,16-bit,73,85
16,exp-114,Qwen-Coder,Big (≥ 7B),5K,HQ,16-bit,72,84
17,exp-109,Qwen-Coder,Big (≥ 7B),1K,ALL,4-bit,71,83
18,exp-111,Qwen-Coder,Big (≥ 7B),1K,ALL,8-bit,70,82
19,exp-114,Qwen,Big (≥ 7B),5K,ALL,16-bit,69,81
20,exp-112,Qwen,Big (≥ 7B),5K,ALL,8-bit,70,80
21,exp-110,Qwen-Coder,Big (≥ 7B),5K,HQ,4-bit,73,80
22,exp-112,Qwen-Coder,Big (≥ 7B),5K,HQ,8-bit,68,80
23,exp-110,Qwen,Big (≥ 7B),5K,HQ,4-bit,68,78
24,exp-109,Qwen,Big (≥ 7B),1K,ALL,4-bit,68,77
25,exp-109,Qwen-Coder,Big (≥ 7B),1K,HQ,4-bit,58,75
26,exp-113,Qwen,Big (≥ 7B),1K,ALL,16-bit,66,74
27,exp-108,Qwen-Coder,Small (< 4B),5K,ALL,16-bit,67,73
28,exp-111,Qwen-Coder,Big (≥ 7B),1K,HQ,8-bit,59,73
29,exp-110,Qwen,Big (≥ 7B),5K,ALL,4-bit,61,73
30,exp-113,Qwen-Coder,Big (≥ 7B),1K,HQ,16-bit,57,73
31,exp-112,Qwen,Big (≥ 7B),5K,HQ,8-bit,60,70
32,exp-111,Qwen,Big (≥ 7B),1K,ALL,8-bit,60,69
33,exp-113,Qwen,Big (≥ 7B),1K,HQ,16-bit,60,67
34,exp-113,Llama,Big (≥ 7B),-,Vanilla,-,0,66
35,exp-109,Llama,Big (≥ 7B),-,Vanilla,-,0,66
36,exp-110,Gemma,Big (≥ 7B),-,Vanilla,-,0,66
37,exp-106,Qwen-Coder,Small (< 4B),5K,ALL,8-bit,61,66
38,exp-111,Qwen,Big (≥ 7B),1K,HQ,8-bit,58,66
39,exp-110,Llama,Big (≥ 7B),-,Vanilla,-,0,66
40,exp-114,Llama,Big (≥ 7B),-,Vanilla,-,0,66
41,exp-109,Gemma,Big (≥ 7B),-,Vanilla,-,0,66
42,exp-111,Llama,Big (≥ 7B),-,Vanilla,-,0,66
43,exp-112,Llama,Big (≥ 7B),-,Vanilla,-,0,66
44,exp-109,Qwen,Big (≥ 7B),1K,HQ,4-bit,56,65
45,exp-111,Llama,Big (≥ 7B),1K,ALL,8-bit,64,65
46,exp-114,Gemma,Big (≥ 7B),-,Vanilla,-,0,65
47,exp-111,Gemma,Big (≥ 7B),-,Vanilla,-,0,65
48,exp-113,Gemma,Big (≥ 7B),-,Vanilla,-,0,65
49,exp-112,Gemma,Big (≥ 7B),-,Vanilla,-,0,65

In [15]:
df_big = df_solved[df_solved["Tier"] == "Big (≥ 7B)"].copy()
df_big = df_big.sort_values(by="after_passed", ascending=False).reset_index(drop=True)

display(df_big.head(30))

,experiment,Architecture,Tier,dataset_size,data_split,quantization,before_passed,after_passed
0,exp-111,Qwen-Coder,Big (≥ 7B),-,Vanilla,-,15,101
1,exp-110,Qwen-Coder,Big (≥ 7B),-,Vanilla,-,15,101
2,exp-109,Qwen-Coder,Big (≥ 7B),-,Vanilla,-,15,101
3,exp-113,Qwen-Coder,Big (≥ 7B),-,Vanilla,-,15,101
4,exp-114,Qwen-Coder,Big (≥ 7B),-,Vanilla,-,15,101
5,exp-112,Qwen-Coder,Big (≥ 7B),-,Vanilla,-,15,101
6,exp-112,Qwen,Big (≥ 7B),-,Vanilla,-,52,86
7,exp-114,Qwen,Big (≥ 7B),-,Vanilla,-,52,86
8,exp-109,Qwen,Big (≥ 7B),-,Vanilla,-,52,86
9,exp-113,Qwen-Coder,Big (≥ 7B),1K,ALL,16-bit,73,86
10,exp-112,Qwen-Coder,Big (≥ 7B),5K,ALL,8-bit,73,86
11,exp-113,Qwen,Big (≥ 7B),-,Vanilla,-,52,86
12,exp-111,Qwen,Big (≥ 7B),-,Vanilla,-,52,86
13,exp-110,Qwen,Big (≥ 7B),-,Vanilla,-,52,86
14,exp-110,Qwen-Coder,Big (≥ 7B),5K,ALL,4-bit,73,85
15,exp-114,Qwen-Coder,Big (≥ 7B),5K,ALL,16-bit,73,85
16,exp-114,Qwen-Coder,Big (≥ 7B),5K,HQ,16-bit,72,84
17,exp-109,Qwen-Coder,Big (≥ 7B),1K,ALL,4-bit,71,83
18,exp-111,Qwen-Coder,Big (≥ 7B),1K,ALL,8-bit,70,82
19,exp-114,Qwen,Big (≥ 7B),5K,ALL,16-bit,69,81
20,exp-112,Qwen-Coder,Big (≥ 7B),5K,HQ,8-bit,68,80
21,exp-112,Qwen,Big (≥ 7B),5K,ALL,8-bit,70,80
22,exp-110,Qwen-Coder,Big (≥ 7B),5K,HQ,4-bit,73,80
23,exp-110,Qwen,Big (≥ 7B),5K,HQ,4-bit,68,78
24,exp-109,Qwen,Big (≥ 7B),1K,ALL,4-bit,68,77
25,exp-109,Qwen-Coder,Big (≥ 7B),1K,HQ,4-bit,58,75
26,exp-113,Qwen,Big (≥ 7B),1K,ALL,16-bit,66,74
27,exp-111,Qwen-Coder,Big (≥ 7B),1K,HQ,8-bit,59,73
28,exp-113,Qwen-Coder,Big (≥ 7B),1K,HQ,16-bit,57,73
29,exp-110,Qwen,Big (≥ 7B),5K,ALL,4-bit,61,73

In [16]:
df_small = df_solved[df_solved["Tier"] == "Small (< 4B)"].copy()
df_small = df_small.sort_values(by="after_passed", ascending=False).reset_index(drop=True)

display(df_small.head(50))

,experiment,Architecture,Tier,dataset_size,data_split,quantization,before_passed,after_passed
0,exp-108,Qwen-Coder,Small (< 4B),5K,ALL,16-bit,67,73
1,exp-106,Qwen-Coder,Small (< 4B),5K,ALL,8-bit,61,66
2,exp-104,Qwen-Coder,Small (< 4B),5K,ALL,4-bit,56,64
3,exp-108,Qwen-Coder,Small (< 4B),5K,HQ,16-bit,54,63
4,exp-105,Qwen-Coder,Small (< 4B),1K,ALL,8-bit,62,62
5,exp-107,Qwen-Coder,Small (< 4B),1K,ALL,16-bit,62,62
6,exp-106,Qwen-Coder,Small (< 4B),5K,HQ,8-bit,49,60
7,exp-104,Qwen-Coder,Small (< 4B),5K,HQ,4-bit,51,58
8,exp-103,Qwen-Coder,Small (< 4B),1K,ALL,4-bit,54,58
9,exp-116,Qwen-Coder,Small (< 4B),1K,HQ,16-bit,45,56
10,exp-104,Phi,Small (< 4B),5K,ALL,4-bit,55,56
11,exp-104,Phi,Small (< 4B),5K,HQ,4-bit,46,54
12,exp-116,Qwen-Coder,Small (< 4B),1K,ALL,16-bit,51,52
13,exp-105,Qwen-Coder,Small (< 4B),1K,HQ,8-bit,49,51
14,exp-107,Qwen-Coder,Small (< 4B),1K,HQ,16-bit,50,50
15,exp-103,Qwen-Coder,Small (< 4B),1K,HQ,4-bit,43,50
16,exp-103,Phi,Small (< 4B),1K,HQ,4-bit,42,49
17,exp-105,Phi,Small (< 4B),1K,ALL,8-bit,46,46
18,exp-117,Qwen-Coder,Small (< 4B),5K,HQ,16-bit,43,46
19,exp-103,Phi,Small (< 4B),-,Vanilla,-,7,45
20,exp-104,Llama,Small (< 4B),5K,HQ,4-bit,44,45
21,exp-108,Phi,Small (< 4B),-,Vanilla,-,7,45
22,exp-105,Phi,Small (< 4B),-,Vanilla,-,7,45
23,exp-104,Phi,Small (< 4B),-,Vanilla,-,7,45
24,exp-107,Phi,Small (< 4B),-,Vanilla,-,7,45
25,exp-103,Phi,Small (< 4B),1K,ALL,4-bit,43,45
26,exp-106,Phi,Small (< 4B),-,Vanilla,-,7,45
27,exp-106,Phi,Small (< 4B),5K,ALL,8-bit,38,42
28,exp-107,Phi,Small (< 4B),1K,ALL,16-bit,41,42
29,exp-117,Qwen-Coder,Small (< 4B),-,Vanilla,-,0,41
30,exp-105,Qwen-Coder,Small (< 4B),-,Vanilla,-,0,41
31,exp-108,Qwen-Coder,Small (< 4B),-,Vanilla,-,0,41
32,exp-116,Qwen-Coder,Small (< 4B),-,Vanilla,-,0,41
33,exp-104,Qwen-Coder,Small (< 4B),-,Vanilla,-,0,41
34,exp-107,Qwen-Coder,Small (< 4B),-,Vanilla,-,0,41
35,exp-105,Phi,Small (< 4B),1K,HQ,8-bit,37,41
36,exp-103,Qwen-Coder,Small (< 4B),-,Vanilla,-,0,41
37,exp-106,Qwen-Coder,Small (< 4B),-,Vanilla,-,0,41
38,exp-106,Phi,Small (< 4B),5K,HQ,8-bit,35,41
39,exp-103,Llama,Small (< 4B),1K,ALL,4-bit,41,41
40,exp-108,Phi,Small (< 4B),5K,HQ,16-bit,36,40
41,exp-107,Phi,Small (< 4B),1K,HQ,16-bit,39,40
42,exp-103,Llama,Small (< 4B),-,Vanilla,-,0,40
43,exp-108,Phi,Small (< 4B),5K,ALL,16-bit,37,40
44,exp-107,Llama,Small (< 4B),-,Vanilla,-,0,39
45,exp-108,Llama,Small (< 4B),-,Vanilla,-,0,39
46,exp-104,Llama,Small (< 4B),-,Vanilla,-,0,39
47,exp-105,Llama,Small (< 4B),-,Vanilla,-,0,39
48,exp-106,Llama,Small (< 4B),-,Vanilla,-,0,39
49,exp-103,Llama,Small (< 4B),1K,HQ,4-bit,38,38