In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import sys
import os
from datasets import load_dataset

root_path = os.path.abspath(os.path.join(".."))
if root_path not in sys.path:
    sys.path.append(root_path)

from utils import standardize_model_names  # noqa: E402

In [2]:
ec_url = "https://huggingface.co/datasets/mehmetdavut/RubyCraft-3.4-Eval-Logs/resolve/main/ec_before_after.csv"
df_ec = pd.read_csv(ec_url)
df_ec = standardize_model_names(df_ec, model_column="model")
df_ec = df_ec[~df_ec["model"].str.contains("teacher", case=False, na=False)].copy()

In [3]:
ic_url = "https://huggingface.co/datasets/mehmetdavut/RubyCraft-3.4-Eval-Logs/resolve/main/ic_before_after.csv"
df_ic = pd.read_csv(ic_url)
df_ic = standardize_model_names(df_ic, model_column="model")
df_ic = df_ic[~df_ic["model"].str.contains("teacher", case=False, na=False)].copy()

In [4]:
dataset_meta = load_dataset("mehmetdavut/RubyCraft-3.4-Eval-Logs", "intrinsic_capability_humaneval", split="train")
df_meta = dataset_meta.to_pandas()
df_meta = standardize_model_names(df_meta, model_column="model_architecture")
df_meta = df_meta[~df_meta["model_role"].str.contains("Teacher", case=False, na=False)].copy()

df_meta["passed_bool"] = df_meta["raw_avg_score"] > 0
meta_grouped = df_meta.groupby(["experiment_id", "Architecture", "dataset_size", "data_split", "quantization"])["passed_bool"].sum().reset_index()
meta_grouped.rename(columns={"passed_bool": "raw_score"}, inplace=True)
meta_grouped = meta_grouped.sort_values(["experiment_id", "Architecture", "raw_score", "data_split"])
meta_grouped["rank"] = meta_grouped.groupby(["experiment_id", "Architecture"])["raw_score"].rank(method="first")

df_ic = df_ic.sort_values(["experiment", "Architecture", "before_passed", "model"])
df_ic["rank"] = df_ic.groupby(["experiment", "Architecture"])["before_passed"].rank(method="first")

df_mapping = df_ic.merge(
    meta_grouped,
    left_on=["experiment", "Architecture", "rank"],
    right_on=["experiment_id", "Architecture", "rank"],
    how="left"
)[["experiment", "model", "Architecture", "dataset_size", "data_split", "quantization"]]

In [5]:
df_merged = df_ec.merge(
    df_mapping,
    on=["experiment", "model", "Architecture"],
    how="left"
)

In [6]:
base_mask = df_merged["data_split"].isna() | (df_merged["data_split"] == "Base")
df_merged.loc[base_mask, "dataset_size"] = "-"
df_merged.loc[base_mask, "data_split"] = "Vanilla"
df_merged.loc[base_mask, "quantization"] = "-"

In [7]:
df_merged["after_style_mean"] = df_merged["after_style_mean"].fillna(0).astype(float)
df_merged["before_style_mean"] = df_merged["before_style_mean"].fillna(0).astype(float)

tier_col = "Tier_x" if "Tier_x" in df_merged.columns else "Tier"

df_solved = df_merged[[
    "experiment", "Architecture", tier_col, 
    "dataset_size", "data_split", "quantization", 
    "before_style_mean", "after_style_mean"
]].copy()

df_solved.rename(columns={tier_col: "Tier"}, inplace=True)
df_solved = df_solved.sort_values(by="before_style_mean", ascending=False).reset_index(drop=True)

display(df_solved.head(50))

,experiment,Architecture,Tier,dataset_size,data_split,quantization,before_style_mean,after_style_mean
0,exp-112,Qwen-Coder,Big (≥ 7B),5K,ALL,8-bit,8.02,8.60
1,exp-114,Qwen-Coder,Big (≥ 7B),5K,ALL,16-bit,7.95,8.40
2,exp-110,Qwen-Coder,Big (≥ 7B),5K,HQ,4-bit,7.83,8.43
3,exp-108,Qwen-Coder,Small (< 4B),5K,HQ,16-bit,7.80,8.30
4,exp-110,Qwen-Coder,Big (≥ 7B),5K,ALL,4-bit,7.79,8.22
5,exp-114,Qwen-Coder,Big (≥ 7B),5K,HQ,16-bit,7.58,8.25
6,exp-105,Qwen-Coder,Small (< 4B),1K,HQ,8-bit,7.52,7.85
7,exp-103,Qwen-Coder,Small (< 4B),1K,HQ,4-bit,7.51,8.01
8,exp-110,Qwen,Big (≥ 7B),5K,HQ,4-bit,7.48,8.02
9,exp-109,Qwen-Coder,Big (≥ 7B),1K,ALL,4-bit,7.48,8.57
10,exp-107,Qwen-Coder,Small (< 4B),1K,HQ,16-bit,7.45,7.78
11,exp-111,Qwen-Coder,Big (≥ 7B),1K,HQ,8-bit,7.42,8.30
12,exp-112,Qwen-Coder,Big (≥ 7B),5K,HQ,8-bit,7.40,8.17
13,exp-112,Qwen,Big (≥ 7B),5K,ALL,8-bit,7.38,7.80
14,exp-106,Qwen-Coder,Small (< 4B),5K,HQ,8-bit,7.30,7.87
15,exp-109,Qwen-Coder,Big (≥ 7B),1K,HQ,4-bit,7.22,8.18
16,exp-104,Qwen-Coder,Small (< 4B),5K,HQ,4-bit,7.20,7.62
17,exp-103,Qwen-Coder,Small (< 4B),1K,ALL,4-bit,7.19,7.62
18,exp-113,Qwen-Coder,Big (≥ 7B),1K,HQ,16-bit,7.18,8.13
19,exp-106,Qwen-Coder,Small (< 4B),5K,ALL,8-bit,7.13,7.60
20,exp-113,Qwen-Coder,Big (≥ 7B),1K,ALL,16-bit,7.03,8.32
21,exp-106,Gemma,Small (< 4B),5K,ALL,8-bit,7.01,7.54
22,exp-112,Qwen,Big (≥ 7B),5K,HQ,8-bit,7.00,7.78
23,exp-107,Qwen-Coder,Small (< 4B),1K,ALL,16-bit,6.96,7.31
24,exp-108,Qwen-Coder,Small (< 4B),5K,ALL,16-bit,6.95,7.43
25,exp-104,Qwen-Coder,Small (< 4B),5K,ALL,4-bit,6.94,7.71
26,exp-114,Qwen,Big (≥ 7B),5K,ALL,16-bit,6.92,7.60
27,exp-114,Qwen,Big (≥ 7B),5K,HQ,16-bit,6.91,8.03
28,exp-111,Qwen-Coder,Big (≥ 7B),1K,ALL,8-bit,6.88,8.27
29,exp-108,Gemma,Small (< 4B),5K,ALL,16-bit,6.86,7.24
30,exp-110,Qwen,Big (≥ 7B),5K,ALL,4-bit,6.84,7.69
31,exp-104,Phi,Small (< 4B),5K,ALL,4-bit,6.81,7.64
32,exp-104,Gemma,Small (< 4B),5K,ALL,4-bit,6.81,7.29
33,exp-105,Gemma,Small (< 4B),1K,HQ,8-bit,6.73,7.50
34,exp-108,Phi,Small (< 4B),5K,HQ,16-bit,6.73,7.38
35,exp-117,Qwen-Coder,Small (< 4B),5K,HQ,16-bit,6.72,6.97
36,exp-105,Qwen-Coder,Small (< 4B),1K,ALL,8-bit,6.65,7.15
37,exp-106,Gemma,Small (< 4B),5K,HQ,8-bit,6.60,7.40
38,exp-109,Qwen,Big (≥ 7B),1K,HQ,4-bit,6.55,7.97
39,exp-107,Gemma,Small (< 4B),1K,ALL,16-bit,6.54,6.83
40,exp-104,Phi,Small (< 4B),5K,HQ,4-bit,6.51,7.21
41,exp-104,Gemma,Small (< 4B),5K,HQ,4-bit,6.49,7.06
42,exp-105,Gemma,Small (< 4B),1K,ALL,8-bit,6.48,7.27
43,exp-108,Gemma,Small (< 4B),5K,HQ,16-bit,6.45,7.10
44,exp-113,Qwen,Big (≥ 7B),1K,ALL,16-bit,6.39,7.78
45,exp-107,Gemma,Small (< 4B),1K,HQ,16-bit,6.39,7.03
46,exp-111,Qwen,Big (≥ 7B),1K,HQ,8-bit,6.38,7.70
47,exp-113,Qwen,Big (≥ 7B),1K,HQ,16-bit,6.37,7.82
48,exp-114,Gemma,Big (≥ 7B),5K,ALL,16-bit,6.35,7.37
49,exp-109,Qwen,Big (≥ 7B),1K,ALL,4-bit,6.35,7.80

In [8]:
df_big = df_solved[df_solved["Tier"] == "Big (≥ 7B)"].copy()

df_big = df_big.sort_values(by="after_style_mean", ascending=False).reset_index(drop=True)

display(df_big.head(30))

,experiment,Architecture,Tier,dataset_size,data_split,quantization,before_style_mean,after_style_mean
0,exp-112,Qwen-Coder,Big (≥ 7B),5K,ALL,8-bit,8.02,8.60
1,exp-109,Qwen-Coder,Big (≥ 7B),1K,ALL,4-bit,7.48,8.57
2,exp-110,Qwen-Coder,Big (≥ 7B),5K,HQ,4-bit,7.83,8.43
3,exp-114,Qwen-Coder,Big (≥ 7B),5K,ALL,16-bit,7.95,8.40
4,exp-113,Qwen-Coder,Big (≥ 7B),1K,ALL,16-bit,7.03,8.32
5,exp-111,Qwen-Coder,Big (≥ 7B),1K,HQ,8-bit,7.42,8.30
6,exp-111,Qwen-Coder,Big (≥ 7B),1K,ALL,8-bit,6.88,8.27
7,exp-114,Qwen-Coder,Big (≥ 7B),5K,HQ,16-bit,7.58,8.25
8,exp-110,Qwen-Coder,Big (≥ 7B),5K,ALL,4-bit,7.79,8.22
9,exp-114,Qwen-Coder,Big (≥ 7B),-,Vanilla,-,4.53,8.21
10,exp-109,Qwen-Coder,Big (≥ 7B),1K,HQ,4-bit,7.22,8.18
11,exp-112,Qwen-Coder,Big (≥ 7B),5K,HQ,8-bit,7.40,8.17
12,exp-113,Qwen-Coder,Big (≥ 7B),1K,HQ,16-bit,7.18,8.13
13,exp-110,Qwen-Coder,Big (≥ 7B),-,Vanilla,-,4.43,8.12
14,exp-111,Gemma,Big (≥ 7B),1K,HQ,8-bit,4.93,8.08
15,exp-112,Qwen-Coder,Big (≥ 7B),-,Vanilla,-,4.40,8.08
16,exp-114,Gemma,Big (≥ 7B),5K,HQ,16-bit,5.19,8.07
17,exp-109,Qwen-Coder,Big (≥ 7B),-,Vanilla,-,4.39,8.07
18,exp-111,Qwen-Coder,Big (≥ 7B),-,Vanilla,-,4.36,8.04
19,exp-114,Qwen,Big (≥ 7B),5K,HQ,16-bit,6.91,8.03
20,exp-110,Qwen,Big (≥ 7B),5K,HQ,4-bit,7.48,8.02
21,exp-113,Qwen-Coder,Big (≥ 7B),-,Vanilla,-,4.31,7.99
22,exp-109,Qwen,Big (≥ 7B),1K,HQ,4-bit,6.55,7.97
23,exp-113,Gemma,Big (≥ 7B),1K,HQ,16-bit,4.14,7.94
24,exp-113,Qwen,Big (≥ 7B),1K,HQ,16-bit,6.37,7.82
25,exp-111,Gemma,Big (≥ 7B),1K,ALL,8-bit,4.81,7.81
26,exp-112,Qwen,Big (≥ 7B),5K,ALL,8-bit,7.38,7.80
27,exp-109,Qwen,Big (≥ 7B),1K,ALL,4-bit,6.35,7.80
28,exp-109,Gemma,Big (≥ 7B),1K,HQ,4-bit,5.39,7.79
29,exp-113,Qwen,Big (≥ 7B),1K,ALL,16-bit,6.39,7.78

In [9]:
df_small = df_solved[df_solved["Tier"] == "Small (< 4B)"].copy()
df_small = df_small.sort_values(by="after_style_mean", ascending=False).reset_index(drop=True)

display(df_small.head(30))

,experiment,Architecture,Tier,dataset_size,data_split,quantization,before_style_mean,after_style_mean
0,exp-108,Qwen-Coder,Small (< 4B),5K,HQ,16-bit,7.80,8.30
1,exp-103,Qwen-Coder,Small (< 4B),1K,HQ,4-bit,7.51,8.01
2,exp-106,Qwen-Coder,Small (< 4B),5K,HQ,8-bit,7.30,7.87
3,exp-105,Qwen-Coder,Small (< 4B),1K,HQ,8-bit,7.52,7.85
4,exp-107,Qwen-Coder,Small (< 4B),1K,HQ,16-bit,7.45,7.78
5,exp-104,Qwen-Coder,Small (< 4B),5K,ALL,4-bit,6.94,7.71
6,exp-104,Phi,Small (< 4B),5K,ALL,4-bit,6.81,7.64
7,exp-104,Qwen-Coder,Small (< 4B),5K,HQ,4-bit,7.20,7.62
8,exp-103,Qwen-Coder,Small (< 4B),1K,ALL,4-bit,7.19,7.62
9,exp-106,Qwen-Coder,Small (< 4B),5K,ALL,8-bit,7.13,7.60
10,exp-106,Gemma,Small (< 4B),5K,ALL,8-bit,7.01,7.54
11,exp-105,Gemma,Small (< 4B),1K,HQ,8-bit,6.73,7.50
12,exp-116,Qwen-Coder,Small (< 4B),1K,HQ,16-bit,5.66,7.47
13,exp-105,Phi,Small (< 4B),1K,HQ,8-bit,6.17,7.47
14,exp-108,Qwen-Coder,Small (< 4B),5K,ALL,16-bit,6.95,7.43
15,exp-106,Gemma,Small (< 4B),5K,HQ,8-bit,6.60,7.40
16,exp-108,Phi,Small (< 4B),5K,HQ,16-bit,6.73,7.38
17,exp-117,Qwen-Coder,Small (< 4B),-,Vanilla,-,3.57,7.37
18,exp-107,Qwen-Coder,Small (< 4B),-,Vanilla,-,3.56,7.36
19,exp-103,Phi,Small (< 4B),1K,HQ,4-bit,6.14,7.36
20,exp-116,Qwen-Coder,Small (< 4B),-,Vanilla,-,3.52,7.32
21,exp-106,Qwen-Coder,Small (< 4B),-,Vanilla,-,3.52,7.32
22,exp-107,Qwen-Coder,Small (< 4B),1K,ALL,16-bit,6.96,7.31
23,exp-103,Phi,Small (< 4B),1K,ALL,4-bit,6.20,7.30
24,exp-104,Gemma,Small (< 4B),5K,ALL,4-bit,6.81,7.29
25,exp-104,Qwen-Coder,Small (< 4B),-,Vanilla,-,3.48,7.28
26,exp-105,Qwen-Coder,Small (< 4B),-,Vanilla,-,3.48,7.28
27,exp-103,Qwen-Coder,Small (< 4B),-,Vanilla,-,3.48,7.28
28,exp-105,Gemma,Small (< 4B),1K,ALL,8-bit,6.48,7.27
29,exp-108,Gemma,Small (< 4B),5K,ALL,16-bit,6.86,7.24